# -*- coding: utf-8 -*-
"""Lab 1 Summarize Dialogue IA LLMs .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHwbi1UmfrL1uLkW8tp3hgBz2SIKfBCM
"""

!pip install -U torch==2.5.1 datasets==2.17.0 transformers==4.38.2

"""**1 - Set up Required Dependencies**"""

import warnings
warnings.filterwarnings("ignore")

from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig

"""**2 - Summarize Dialogue without Prompt Engineering**"""

huggingface_dataset_name = "knkarthick/dialogsum"

dataset = load_dataset(huggingface_dataset_name)

example_indices = [40, 200]

dash_line = '-'.join('' for x in range(100))

for i, index in enumerate(example_indices):
    print(dash_line)
    print('Example ', i + 1)
    print(dash_line)
    print('INPUT DIALOGUE:')
    print(dataset['test'][index]['dialogue'])
    print(dash_line)
    print('BASELINE HUMAN SUMMARY:')
    print(dataset['test'][index]['summary'])
    print(dash_line)
    print()

model_name = 'google/flan-t5-base'

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

sentence = "What time is it, Tom?"

sentence_encoded = tokenizer(sentence, return_tensors='pt')

sentence_decoded = tokenizer.decode(
        sentence_encoded["input_ids"][0],
        skip_special_tokens=True
    )

print('ENCODED SENTENCE:')
print(sentence_encoded["input_ids"][0])
print('\nDECODED SENTENCE:')
print(sentence_decoded)

for i, index in enumerate(example_indices):
    dialogue = dataset['test'][index]['dialogue']
    summary = dataset['test'][index]['summary']

    inputs = tokenizer(dialogue, return_tensors='pt')
    output = tokenizer.decode(
        model.generate(
            inputs["input_ids"],
            max_new_tokens=50,
        )[0],
        skip_special_tokens=True
    )

    print(dash_line)
    print('Example ', i + 1)
    print(dash_line)
    print(f'INPUT PROMPT:\n{dialogue}')
    print(dash_line)
    print(f'BASELINE HUMAN SUMMARY:\n{summary}')
    print(dash_line)
    print(f'MODEL GENERATION - WITHOUT PROMPT ENGINEERING:\n{output}\n')

"""**3 - Summarize Dialogue with an Instruction Prompt**  

**3.1 — Zero Shot Inference with an Instruction Prompt.**
"""

for i, index in enumerate(example_indices):
    dialogue = dataset['test'][index]['dialogue']
    summary = dataset['test'][index]['summary']

    prompt = f"""
Summarize the following conversation.

{dialogue}

Summary:
    """

    inputs = tokenizer(prompt, return_tensors='pt')
    output = tokenizer.decode(
        model.generate(
            inputs["input_ids"],
            max_new_tokens=50,
        )[0],
        skip_special_tokens=True
    )

    print(dash_line)
    print('Example ', i + 1)
    print(dash_line)
    print(f'INPUT PROMPT:\n{prompt}')
    print(dash_line)
    print(f'BASELINE HUMAN SUMMARY:\n{summary}')
    print(dash_line)
    print(f'MODEL GENERATION - ZERO SHOT:\n{output}\n')

"""Zero-shot prompting improves the model output because the instruction tells the model what task to perform. Without prompt engineering, FLAN-T5 tends to generate a continuation or extract a sentence from the dialogue. With an instruction prompt, the model produces a more summary-like response.

**3.2 — Zero Shot Inference with the Prompt Template from FLAN-T5:**
"""

for i, index in enumerate(example_indices):
    dialogue = dataset['test'][index]['dialogue']
    summary = dataset['test'][index]['summary']

    prompt = f"""
Dialogue:

{dialogue}

What was going on?
"""

    inputs = tokenizer(prompt, return_tensors='pt')
    output = tokenizer.decode(
        model.generate(
            inputs["input_ids"],
            max_new_tokens=50,
        )[0],
        skip_special_tokens=True
    )

    print(dash_line)
    print('Example ', i + 1)
    print(dash_line)
    print(f'INPUT PROMPT:\n{prompt}')
    print(dash_line)
    print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')
    print(dash_line)
    print(f'MODEL GENERATION - ZERO SHOT:\n{output}\n')

"""The FLAN-T5 prompt template works and generates task-related outputs, but it does not always improve the quality of the summary. In Example 1, the model captures the topic but misidentifies who is late. In Example 2, the model mostly repeats dialogue content instead of producing a concise summary. This shows that prompt templates can help, but they do not guarantee perfect summarization.

**4 — Summarize Dialogue with One Shot and Few Shot Inference**

**4.1 — One Shot Inference.**
"""

def make_prompt(example_indices_full, example_index_to_summarize):
    prompt = ''
    for index in example_indices_full:
        dialogue = dataset['test'][index]['dialogue']
        summary = dataset['test'][index]['summary']

        prompt += f"""
Dialogue:

{dialogue}

What was going on?
{summary}


"""

    dialogue = dataset['test'][example_index_to_summarize]['dialogue']

    prompt += f"""
Dialogue:

{dialogue}

What was going on?
"""

    return prompt

example_indices_full = [40]
example_index_to_summarize = 200

one_shot_prompt = make_prompt(example_indices_full, example_index_to_summarize)

print(one_shot_prompt)

summary = dataset['test'][example_index_to_summarize]['summary']

inputs = tokenizer(one_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        max_new_tokens=50,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')
print(dash_line)
print(f'MODEL GENERATION - ONE SHOT:\n{output}')

"""One-shot inference improved the model output because the model received one complete example of the expected task format. The generated summary became more complete than the zero-shot output, but it still contained some role confusion and was less concise than the human baseline.

**4.2 — Few Shot Inference**
"""

example_indices_full = [40, 80, 120]
example_index_to_summarize = 200

few_shot_prompt = make_prompt(example_indices_full, example_index_to_summarize)

print(few_shot_prompt)

summary = dataset['test'][example_index_to_summarize]['summary']

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        max_new_tokens=50,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')
print(dash_line)
print(f'MODEL GENERATION - FEW SHOT:\n{output}')

"""Few-shot inference did not significantly improve the output in this case. The prompt exceeded the model context length limit, reaching 819 tokens while the model limit is 512 tokens. Because of this, part of the prompt may be ignored, and the generated summary may become less reliable. This shows that adding more examples does not always improve performance, especially when the context window is exceeded.

**few-shot with 2 examples**
"""

example_indices_full = [40, 80]
example_index_to_summarize = 200

few_shot_prompt = make_prompt(example_indices_full, example_index_to_summarize)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        max_new_tokens=50,
    )[0],
    skip_special_tokens=True
)

summary = dataset['test'][example_index_to_summarize]['summary']

print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')
print(dash_line)
print(f'MODEL GENERATION - FEW SHOT 2 EXAMPLES:\n{output}')

"""Using two few-shot examples produced a valid result without exceeding the model context window. The output captured the main topic of the dialogue, which was upgrading software and hardware, but it still showed some role confusion and was less concise than the human baseline. This confirms that few-shot prompting can help guide the model, but adding more examples is only useful when the prompt remains within the model context length.

**5 - Generative Configuration Parameters for Inference**
"""

generation_config = GenerationConfig(max_new_tokens=50)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'MODEL GENERATION - FEW SHOT:\n{output}')
print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')

generation_config = GenerationConfig(max_new_tokens=10)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'MODEL GENERATION - MAX 10 TOKENS:\n{output}')
print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')

generation_config = GenerationConfig(
    max_new_tokens=50,
    do_sample=True,
    temperature=0.1
)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'MODEL GENERATION - TEMPERATURE 0.1:\n{output}')
print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')

generation_config = GenerationConfig(
    max_new_tokens=50,
    do_sample=True,
    temperature=0.5
)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'MODEL GENERATION - TEMPERATURE 0.5:\n{output}')
print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')

generation_config = GenerationConfig(
    max_new_tokens=50,
    do_sample=True,
    temperature=1.0
)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print(f'MODEL GENERATION - TEMPERATURE 1.0:\n{output}')
print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')

generation_config = GenerationConfig(max_new_tokens=50)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print("MODEL GENERATION - BASE CONFIG:")
print(output)
print(dash_line)
print(f"BASELINE HUMAN SUMMARY:\n{summary}")

generation_config = GenerationConfig(
    max_new_tokens=50,
    do_sample=True,
    temperature=0.1
)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')
output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print("MODEL GENERATION - TEMPERATURE 0.1:")
print(output)
print(dash_line)
print(f"BASELINE HUMAN SUMMARY:\n{summary}")

generation_config = GenerationConfig(
    max_new_tokens=50,
    do_sample=True,
    temperature=0.5
)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')

output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print("MODEL GENERATION - TEMPERATURE 0.5:")
print(output)
print(dash_line)
print(f"BASELINE HUMAN SUMMARY:\n{summary}")

generation_config = GenerationConfig(
    max_new_tokens=50,
    do_sample=True,
    temperature=1.0
)

inputs = tokenizer(few_shot_prompt, return_tensors='pt')

output = tokenizer.decode(
    model.generate(
        inputs["input_ids"],
        generation_config=generation_config,
    )[0],
    skip_special_tokens=True
)

print(dash_line)
print("MODEL GENERATION - TEMPERATURE 1.0:")
print(output)
print(dash_line)
print(f"BASELINE HUMAN SUMMARY:\n{summary}")

"""**Conclusions:**

* This lab showed that prompt engineering significantly affects the quality of   LLM outputs in dialogue summarization.

* Without prompt engineering, FLAN-T5 did not clearly understand the summarization task and generated incomplete or dialogue-like outputs.

* With zero-shot prompting, the model improved because the instruction explicitly told it to summarize the conversation.

* Using a FLAN-T5 prompt template changed the model behavior, but did not always improve quality. In some cases, the model captured the general topic but confused the speakers or repeated parts of the dialogue.

* One-shot inference improved the output by giving the model one complete example of the expected task format. Few-shot inference also helped, but too many examples exceeded the context window. Using two examples was more stable than three because it stayed within the model limit.

* Generation parameters also changed the output. A low temperature produced conservative and stable text, while temperature 0.5 generated a cleaner and more concise summary. Temperature 1.0 produced more flexible text but reduced factual precision and moved away from the summarization task.

* Overall, the lab demonstrates that better prompts, controlled examples, and appropriate generation settings can improve LLM outputs, but they do not guarantee perfect results.
"""