# -*- coding: utf-8 -*-
"""Lab 3 Fine-Tune FLAN-T5 with PPO and PEFT to Generate Less-Toxic Summaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTDdXLiuz-7KFswZTymOWt91iNTUuR6n

**1 — Set up Required Dependencies**
"""

!pip install -U --quiet \
    torch==2.5.1 \
    datasets==2.17.0 \
    transformers==4.38.2 \
    evaluate==0.4.0 \
    peft==0.3.0 \
    trl==0.4.2 \
    rouge_score==0.1.2

!pip install -U --quiet \
    numpy==1.26.4 \
    pandas==2.2.2 \
    pyarrow==18.1.0

import numpy as np
import pandas as pd
import torch
import transformers
import datasets
import evaluate
import peft
import trl

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("evaluate:", evaluate.__version__)
print("peft:", peft.__version__)
print("trl:", trl.__version__)

"""**Notes**

* Colab showed dependency warnings because it already has many pre-installed libraries with different version requirements. These warnings do not necessarily mean the lab failed. After restarting the runtime, the imports worked correctly, so the environment is ready for the lab.

* The required libraries were installed and verified successfully. The environment is ready to work with FLAN-T5, PEFT, TRL, PPO, and toxicity evaluation.

**2 - Load FLAN-T5 Model, Prepare Reward Model and Toxicity Evaluato**

**2.1 — Load Data and FLAN-T5 Model**
"""

import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import warnings
warnings.filterwarnings("ignore")

from transformers import (
    pipeline,
    AutoTokenizer,
    AutoModelForSequenceClassification,
    AutoModelForSeq2SeqLM,
    GenerationConfig
)

from datasets import load_dataset
from peft import PeftModel, PeftConfig, LoraConfig, TaskType

from trl import PPOTrainer, PPOConfig, AutoModelForSeq2SeqLMWithValueHead
from trl import create_reference_model
from trl.core import LengthSampler

import torch
import evaluate
import numpy as np
import pandas as pd

from tqdm import tqdm
tqdm.pandas()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

model_name = "google/flan-t5-base"
huggingface_dataset_name = "knkarthick/dialogsum"

def build_dataset(model_name,
                  dataset_name,
                  input_min_text_length,
                  input_max_text_length):

    """
    Preprocess the dataset and split it into train and test parts.

    This function:
    1. Loads the DialogSum train split.
    2. Filters dialogues by length.
    3. Wraps each dialogue in a summarization instruction.
    4. Tokenizes the prompt.
    5. Creates a 'query' field required by PPOTrainer.
    6. Splits the dataset into train and test sets.
    """

    dataset = load_dataset(dataset_name, split="train")

    dataset = dataset.filter(
        lambda x: len(x["dialogue"]) > input_min_text_length
        and len(x["dialogue"]) <= input_max_text_length,
        batched=False
    )

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    def tokenize(sample):
        prompt = f"""
Summarize the following conversation.

{sample["dialogue"]}

Summary:
"""
        sample["input_ids"] = tokenizer.encode(prompt)

        # PPOTrainer expects this field to be called "query"
        sample["query"] = tokenizer.decode(sample["input_ids"])

        return sample

    dataset = dataset.map(tokenize, batched=False)
    dataset.set_format(type="torch")

    dataset_splits = dataset.train_test_split(
        test_size=0.2,
        shuffle=False,
        seed=42
    )

    return dataset_splits

dataset = build_dataset(
    model_name=model_name,
    dataset_name=huggingface_dataset_name,
    input_min_text_length=200,
    input_max_text_length=1000
)

print(dataset)
print("\nExample query:")
print(dataset["train"][0]["query"][:500])

"""**Notes**

* In this step, the DialogSum dataset is transformed into instruction-style prompts. The model does not receive raw dialogue only; it receives a task instruction plus the dialogue. The 'input_ids' field contains the tokenized prompt, while the 'query' field keeps the decoded text version required by PPOTrainer.

* The DialogSum dataset was loaded, filtered by dialogue length, converted into summarization prompts, tokenized, and split into train and test sets. This prepares the input format required for PPO-based fine-tuning.

**Load PEFT FLAN-T5 and Create PPO/Reference Models**

**Create Local PEFT FLAN-T5 Model for PPO**

**Notes:**

* The original lab expects a pre-trained PEFT adapter checkpoint to already exist in the environment. In my personal Colab runtime, that checkpoint folder was not available, so the notebook could not load it directly. This is not a coding error; it is an environment/resource availability issue.
"""

!ls -al ./peft-dialogue-summary-checkpoint-from-s3/

!ls -alh ./peft-dialogue-summary-checkpoint-from-s3/adapter_model.bin

from peft import get_peft_model

def print_number_of_trainable_model_parameters(model):
    trainable_model_params = 0
    all_model_params = 0

    for _, param in model.named_parameters():
        all_model_params += param.numel()
        if param.requires_grad:
            trainable_model_params += param.numel()

    percentage = 100 * trainable_model_params / all_model_params

    return f"""
trainable model parameters: {trainable_model_params}
all model parameters: {all_model_params}
percentage of trainable model parameters: {percentage:.2f}%
"""

lora_config = LoraConfig(
    r=32,
    lora_alpha=32,
    target_modules=["q", "v"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM
)

base_model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    torch_dtype=torch.float32
)

peft_model = get_peft_model(base_model, lora_config)

print("PEFT model parameters to be updated:")
print(print_number_of_trainable_model_parameters(peft_model))

"""**Notes**

* Since the pre-trained PEFT checkpoint was not available in the personal Colab environment, a local LoRA adapter was created on top of FLAN-T5. This keeps the educational flow of the lab: using PEFT to train only a small percentage of model parameters before applying PPO.

* A local LoRA adapter was created on top of FLAN-T5 because the original pre-trained PEFT checkpoint was not available in this Colab environment. Only 1.41% of the model parameters are trainable, which shows how PEFT reduces the number of parameters that need to be updated.

**Create PPO Model and Frozen Reference Model**
"""

ppo_model = AutoModelForSeq2SeqLMWithValueHead.from_pretrained(
    peft_model,
    torch_dtype=torch.float32,
    is_trainable=True
)

print("PPO model parameters to be updated:")
print(print_number_of_trainable_model_parameters(ppo_model))

print("\nValue head:")
print(ppo_model.v_head)

ref_model = create_reference_model(ppo_model)

print("Reference model parameters to be updated:")
print(print_number_of_trainable_model_parameters(ref_model))

"""**Notes**

* The PPO model is the trainable policy that will be optimized using rewards from the toxicity model. The reference model is a frozen copy of the initial policy. It is used during PPO to control how much the optimized model deviates from the original model.

* The PPO model was created successfully from the PEFT model. It remains trainable and includes a ValueHead, which is used during reinforcement learning. A frozen reference model was also created with 0 trainable parameters. This reference model represents the original policy and helps control how much the PPO model changes during training.

**2.2 — Prepare Reward Model**
"""

toxicity_model_name = "facebook/roberta-hate-speech-dynabench-r4-target"

toxicity_tokenizer = AutoTokenizer.from_pretrained(toxicity_model_name)
toxicity_model = AutoModelForSequenceClassification.from_pretrained(
    toxicity_model_name
).to(device)

print("Reward model labels:")
print(toxicity_model.config.id2label)

non_toxic_text = "#Person 1# tells Tommy that he didn't like the movie."

toxicity_input_ids = toxicity_tokenizer(
    non_toxic_text,
    return_tensors="pt"
).input_ids.to(device)

logits = toxicity_model(input_ids=toxicity_input_ids).logits

print(f"logits [not hate, hate]: {logits.tolist()[0]}")

probabilities = logits.softmax(dim=-1).tolist()[0]
print(f"probabilities [not hate, hate]: {probabilities}")

not_hate_index = 0
nothate_reward = logits[:, not_hate_index].tolist()
print(f"reward (high): {nothate_reward}")

toxic_text = "#Person 1# tells Tommy that the movie was terrible, dumb and stupid."

toxicity_input_ids = toxicity_tokenizer(
    toxic_text,
    return_tensors="pt"
).input_ids.to(device)

logits = toxicity_model(input_ids=toxicity_input_ids).logits

print(f"logits [not hate, hate]: {logits.tolist()[0]}")

probabilities = logits.softmax(dim=-1).tolist()[0]
print(f"probabilities [not hate, hate]: {probabilities}")

nothate_reward = logits[:, not_hate_index].tolist()
print(f"reward (low): {nothate_reward}")

device_id = 0 if torch.cuda.is_available() else -1

sentiment_pipe = pipeline(
    "sentiment-analysis",
    model=toxicity_model_name,
    device=device_id,
    framework="pt"
)

reward_logits_kwargs = {
    "top_k": None,
    "function_to_apply": "none",
    "batch_size": 16
}

reward_probabilities_kwargs = {
    "top_k": None,
    "function_to_apply": "softmax",
    "batch_size": 16
}

print("Reward model output:")
print("For non-toxic text:")
print(sentiment_pipe(non_toxic_text, **reward_logits_kwargs))
print(sentiment_pipe(non_toxic_text, **reward_probabilities_kwargs))

print("\nFor toxic text:")
print(sentiment_pipe(toxic_text, **reward_logits_kwargs))
print(sentiment_pipe(toxic_text, **reward_probabilities_kwargs))

"""**Notes**

* The reward model is a RoBERTa-based hate speech classifier. It predicts two labels: nothate and hate. In this lab, the raw logit for the nothate class is used as the positive reward signal. PPO will use this reward to encourage the language model to generate less toxic summaries.

*  The toxicity reward model was prepared and tested with non-toxic and more negative examples. The nothate logit will be used as the reward signal during PPO fine-tuning.

* The reward model was loaded successfully. It classifies text into two labels: nothate and hate. The non-toxic example received a high nothate probability and a high reward, while the more negative example received a lower nothate score and a lower reward. This confirms that the nothate logit can be used as the positive reward signal for PPO.

**2.3 — Evaluate Toxicity Before Detoxification**
"""

toxicity_evaluator = evaluate.load(
    "toxicity",
    toxicity_model_name,
    module_type="measurement",
    toxic_label="hate"
)

print("Toxicity evaluator loaded.")

toxicity_score = toxicity_evaluator.compute(
    predictions=[non_toxic_text]
)

print("Toxicity score for non-toxic text:")
print(toxicity_score["toxicity"])

toxicity_score = toxicity_evaluator.compute(
    predictions=[toxic_text]
)

print("\nToxicity score for toxic text:")
print(toxicity_score["toxicity"])

def evaluate_toxicity(model,
                      toxicity_evaluator,
                      tokenizer,
                      dataset,
                      num_samples=5):
    """
    Evaluates the average toxicity of generated summaries.

    Steps:
    1. Takes prompts from the dataset.
    2. Uses the model to generate summaries.
    3. Combines prompt + generated summary.
    4. Measures toxicity using the toxicity evaluator.
    5. Returns mean and standard deviation.
    """

    max_new_tokens = 80
    model = model.to(device)
    model.eval()

    toxicities = []

    for i, sample in tqdm(enumerate(dataset)):
        if i >= num_samples:
            break

        input_text = sample["query"]

        input_ids = tokenizer(
            input_text,
            return_tensors="pt",
            padding=True,
            truncation=True
        ).input_ids.to(device)

        generation_config = GenerationConfig(
            max_new_tokens=max_new_tokens,
            top_k=0.0,
            top_p=1.0,
            do_sample=True
        )

        with torch.no_grad():
            response_token_ids = model.generate(
                input_ids=input_ids,
                generation_config=generation_config
            )

        generated_text = tokenizer.decode(
            response_token_ids[0].cpu(),
            skip_special_tokens=True
        )

        toxicity_score = toxicity_evaluator.compute(
            predictions=[input_text + " " + generated_text]
        )

        toxicities.extend(toxicity_score["toxicity"])

        print(f"\nExample {i+1}")
        print("Generated summary:", generated_text[:300])
        print("Toxicity:", toxicity_score["toxicity"][0])

    mean = np.mean(toxicities)
    std = np.std(toxicities)

    return mean, std

tokenizer = AutoTokenizer.from_pretrained(model_name)

mean_before_detoxification, std_before_detoxification = evaluate_toxicity(
    model=ref_model,
    toxicity_evaluator=toxicity_evaluator,
    tokenizer=tokenizer,
    dataset=dataset["test"],
    num_samples=5
)

print(f"\nToxicity [mean, std] before detoxification:")
print(f"[{mean_before_detoxification}, {std_before_detoxification}]")

"""**Notes**

* The toxicity evaluator was used to measure the baseline toxicity of the model before PPO detoxification. This baseline is important because it gives a reference point to compare against the model after reinforcement learning fine-tuning.

* Before PPO training, the reference model was evaluated to measure its initial toxicity score. This baseline will later be compared with the toxicity score after detoxification.

* The toxicity evaluator was tested successfully. The non-toxic example received a very low toxicity score, while the more toxic example received a much higher score. Then, the reference model was evaluated before PPO detoxification. The baseline mean toxicity was 0.0066 with a standard deviation of 0.0095. This baseline will be used later to compare the model before and after PPO training.

* The baseline toxicity score before detoxification was measured successfully. The model already produced low-toxicity summaries in this small sample, so the initial toxicity mean is very low.

**3 — Perform Fine-Tuning to Detoxify the Summaries**

**3.1 — Initialize PPOTrainer**
"""

def collator(data):
    return dict((key, [d[key] for d in data]) for key in data[0])

test_data = [
    {
        "key1": "value1",
        "key2": "value2",
        "key3": "value3"
    }
]

print("Collator input:")
print(test_data)

print("\nCollator output:")
print(collator(test_data))

"""**PPO Trainer Configuration**"""

learning_rate = 1.41e-5
max_ppo_epochs = 1
mini_batch_size = 2
batch_size = 4

config = PPOConfig(
    model_name=model_name,
    learning_rate=learning_rate,
    ppo_epochs=max_ppo_epochs,
    mini_batch_size=mini_batch_size,
    batch_size=batch_size
)

ppo_trainer = PPOTrainer(
    config=config,
    model=ppo_model,
    ref_model=ref_model,
    tokenizer=tokenizer,
    dataset=dataset["train"],
    data_collator=collator
)

print("PPOTrainer initialized successfully.")

"""**Notes**

* The PPOTrainer was initialized with the trainable PPO model, the frozen reference model, the tokenizer, the training dataset, and a collator. PPOConfig defines the reinforcement learning training settings such as learning rate, PPO epochs, batch size, and mini-batch size.

* PPOTrainer is now ready to coordinate PPO training. It will generate summaries, compare the PPO model with the reference model, receive rewards from the toxicity model, and update the trainable policy.

* The PPOTrainer was initialized successfully. The collator transforms a list of examples into a batch dictionary, and PPOTrainer connects the trainable PPO model, the frozen reference model, the tokenizer, and the training dataset. This prepares the notebook for PPO fine-tuning.

**3.2 — Fine-Tune the Model with PPO**
"""

output_min_length = 20
output_max_length = 80
output_length_sampler = LengthSampler(output_min_length, output_max_length)

generation_kwargs = {
    "min_length": 5,
    "top_k": 0.0,
    "top_p": 1.0,
    "do_sample": True
}

reward_kwargs = {
    "top_k": None,
    "function_to_apply": "none",
    "batch_size": 4
}

max_ppo_steps = 3

print("PPO training settings ready.")
print("max_ppo_steps:", max_ppo_steps)
print("output length range:", output_min_length, "-", output_max_length)

ppo_model.train()

for step, batch in tqdm(enumerate(ppo_trainer.dataloader)):
    if step >= max_ppo_steps:
        break

    prompt_tensors = batch["input_ids"]

    summary_tensors = []

    for prompt_tensor in prompt_tensors:
        max_new_tokens = output_length_sampler()

        generation_kwargs["max_new_tokens"] = max_new_tokens

        summary = ppo_trainer.generate(
            prompt_tensor,
            **generation_kwargs
        )

        summary_tensors.append(summary.squeeze()[-max_new_tokens:])

    batch["response"] = [
        tokenizer.decode(r.squeeze(), skip_special_tokens=True)
        for r in summary_tensors
    ]

    query_response_pairs = [
        q + " " + r
        for q, r in zip(batch["query"], batch["response"])
    ]

    rewards = sentiment_pipe(
        query_response_pairs,
        **reward_kwargs
    )

    reward_tensors = [
        torch.tensor(reward[not_hate_index]["score"])
        for reward in rewards
    ]

    stats = ppo_trainer.step(
        prompt_tensors,
        summary_tensors,
        reward_tensors
    )

    ppo_trainer.log_stats(stats, batch, reward_tensors)

    print(f"\nSTEP {step + 1}")
    print("Sample response:", batch["response"][0][:300])
    print("Sample reward:", reward_tensors[0].item())
    print(f'objective/kl: {stats["objective/kl"]}')
    print(f'ppo/returns/mean: {stats["ppo/returns/mean"]}')
    print(f'ppo/policy/advantages_mean: {stats["ppo/policy/advantages_mean"]}')
    print("-" * 80)

print("PPO training finished.")

"""**Notes**

* During PPO fine-tuning, the model generates summaries for the prompts, the reward model scores each prompt-response pair, and the nothate logit is used as the reward. PPO then updates the trainable policy to encourage responses with higher non-toxic rewards while keeping the model close to the frozen reference model.

* PPO training was successfully executed. The model received reward signals from the toxicity classifier and updated its trainable PEFT/PPO parameters to encourage less toxic outputs.

**3.3 — Evaluate the Model Quantitatively**
"""

mean_after_detoxification, std_after_detoxification = evaluate_toxicity(
    model=ppo_model,
    toxicity_evaluator=toxicity_evaluator,
    tokenizer=tokenizer,
    dataset=dataset["test"],
    num_samples=5
)

print(f"\nToxicity [mean, std] after detoxification:")
print(f"[{mean_after_detoxification}, {std_after_detoxification}]")

mean_improvement = (
    (mean_before_detoxification - mean_after_detoxification)
    / mean_before_detoxification
)

std_improvement = (
    (std_before_detoxification - std_after_detoxification)
    / std_before_detoxification
)

print("Toxicity comparison:")
print(f"Before mean toxicity: {mean_before_detoxification}")
print(f"After mean toxicity:  {mean_after_detoxification}")
print(f"Before std toxicity:  {std_before_detoxification}")
print(f"After std toxicity:   {std_after_detoxification}")

print("\nPercentage improvement of toxicity score after detoxification:")
print(f"mean: {mean_improvement * 100:.2f}%")
print(f"std:  {std_improvement * 100:.2f}%")

"""**Notes**

* The PPO model was evaluated after detoxification using the same toxicity evaluator and the same number of samples as the baseline. The before and after toxicity scores are compared to estimate whether PPO reduced the average toxicity. Since this was a lightweight educational run with only 3 PPO steps, the improvement may be small, unstable, or even negative.

* The PPO model was evaluated after detoxification using the same toxicity evaluator and the same number of samples as the baseline. The before and after toxicity scores are compared to estimate whether PPO reduced the average toxicity. Since this was a lightweight educational run with only 3 PPO steps, the improvement may be small, unstable, or even negative.

* The quantitative evaluation shows a small reduction in average toxicity after PPO fine-tuning. This confirms that the reward-based training loop can influence the model toward less toxic outputs, even in a lightweight educational setup.

**3.4 — Evaluate the Model Qualitatively**
"""

batch_size = 5
compare_results = {}

df_batch = dataset["test"][0:batch_size]

compare_results["query"] = df_batch["query"]
prompt_tensors = df_batch["input_ids"]

summary_tensors_ref = []
summary_tensors_ppo = []

ref_model.eval()
ppo_model.eval()

for i in tqdm(range(batch_size)):
    gen_len = output_length_sampler()
    generation_kwargs["max_new_tokens"] = gen_len

    with torch.no_grad():
        summary_ref = ref_model.generate(
            input_ids=torch.as_tensor(prompt_tensors[i]).unsqueeze(dim=0).to(device),
            **generation_kwargs
        ).squeeze()[-gen_len:]

        summary_ppo = ppo_model.generate(
            input_ids=torch.as_tensor(prompt_tensors[i]).unsqueeze(dim=0).to(device),
            **generation_kwargs
        ).squeeze()[-gen_len:]

    summary_tensors_ref.append(summary_ref)
    summary_tensors_ppo.append(summary_ppo)

compare_results["response_before"] = [
    tokenizer.decode(summary_tensors_ref[i], skip_special_tokens=True)
    for i in range(batch_size)
]

compare_results["response_after"] = [
    tokenizer.decode(summary_tensors_ppo[i], skip_special_tokens=True)
    for i in range(batch_size)
]

texts_before = [
    q + " " + s
    for q, s in zip(compare_results["query"], compare_results["response_before"])
]

texts_after = [
    q + " " + s
    for q, s in zip(compare_results["query"], compare_results["response_after"])
]

rewards_before = sentiment_pipe(texts_before, **reward_kwargs)
rewards_after = sentiment_pipe(texts_after, **reward_kwargs)

compare_results["reward_before"] = [
    reward[not_hate_index]["score"]
    for reward in rewards_before
]

compare_results["reward_after"] = [
    reward[not_hate_index]["score"]
    for reward in rewards_after
]

print("Qualitative comparison generated.")

pd.set_option("display.max_colwidth", 500)

df_compare_results = pd.DataFrame(compare_results)

df_compare_results["reward_diff"] = (
    df_compare_results["reward_after"]
    - df_compare_results["reward_before"]
)

df_compare_results_sorted = (
    df_compare_results
    .sort_values(by=["reward_diff"], ascending=False)
    .reset_index(drop=True)
)

df_compare_results_sorted[
    [
        "response_before",
        "response_after",
        "reward_before",
        "reward_after",
        "reward_diff"
    ]
]

"""**Conclusion Notes**

* The qualitative evaluation compares generated summaries before and after PPO fine-tuning. For each example, the reference model response and the PPO model response are scored by the reward model. The reward_diff column shows whether the PPO response received a higher nothate reward than the original response.

* The qualitative evaluation compared summaries generated before and after PPO fine-tuning. In 3 out of 5 examples, the PPO model received a higher nothate reward than the reference model. Some examples still received lower rewards, which is expected because this was a lightweight run with only 3 PPO steps and a locally created LoRA adapter.

* The qualitative comparison shows that PPO changed the generated summaries and improved the non-toxic reward in several examples. However, the results are not perfect because the training was intentionally lightweight.

* In this lab, FLAN-T5 was adapted using PEFT/LoRA and optimized with PPO to generate less toxic summaries. A RoBERTa hate-speech classifier was used as the reward model, where the nothate logit served as the positive reward signal. The model was evaluated before and after PPO using toxicity scores and qualitative reward comparisons. In the lightweight Colab version, the mean toxicity decreased by 6.46%, and several generated responses received higher nothate rewards after PPO.

* RLHF-style training can use a reward model to guide an LLM toward safer or more preferred outputs, while PEFT makes the process more efficient by updating only a small percentage of model parameters.
"""