# -*- coding: utf-8 -*-
"""Lab_2_Fine_Tune_Generative_Ai_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/159VdrM9SHYZmtwuEjmaFPfHG5g73xMwm

**1 - Set up Load Required Dependencies, Dataset and LLM**

**1.1 - Set up Required Dependencies**
"""

import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import warnings
warnings.filterwarnings("ignore")

from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig, TrainingArguments, Trainer
import torch
import time
import evaluate
import pandas as pd
import numpy as np

import numpy as np
import pandas as pd
import torch
import transformers
import datasets
import evaluate
import peft

print("numpy:", np.__version__)
print("pandas:", pd.__version__)
print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("datasets:", datasets.__version__)
print("evaluate:", evaluate.__version__)
print("peft:", peft.__version__)

"""**Notes**

* The dependency installation completed successfully, although Colab showed compatibility warnings because some pre-installed packages expected different versions. These warnings are not blocking as long as the required lab imports run correctly.

* The environment was successfully configured after restarting the runtime. The required libraries for full fine-tuning, ROUGE evaluation, and PEFT/LoRA are now correctly available.

**1.2 - Load Dataset and LLM**
"""

from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, GenerationConfig, TrainingArguments, Trainer
import torch
import time
import evaluate
import pandas as pd
import numpy as np

huggingface_dataset_name = "knkarthick/dialogsum"

dataset = load_dataset(huggingface_dataset_name)

dataset

model_name = 'google/flan-t5-base'

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

original_model = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16
).to(device)

tokenizer = AutoTokenizer.from_pretrained(model_name, device_map="auto")

"""**Notes**

The DialogSum dataset and the original FLAN-T5 model were loaded successfully. The dataset provides dialogue-summary pairs for training and evaluation, while FLAN-T5 serves as the base sequence-to-sequence model that will later be compared against full fine-tuning and PEFT/LoRA approaches.
"""

def print_number_of_trainable_model_parameters(model):
    trainable_model_params = 0
    all_model_params = 0
    for _, param in model.named_parameters():
        all_model_params += param.numel()
        if param.requires_grad:
            trainable_model_params += param.numel()
    return f"trainable model parameters: {trainable_model_params}\nall model parameters: {all_model_params}\npercentage of trainable model parameters: {100 * trainable_model_params / all_model_params:.2f}%"

print(print_number_of_trainable_model_parameters(original_model))

"""**Notes**

The original FLAN-T5 model has 247,577,856 parameters, and 100% of them are trainable. This means that full fine-tuning would update the entire model, which can improve task performance but requires more compute and memory resources.

**1.3 — Test the Model with Zero Shot Inferencing**
"""

index = 200

dialogue = dataset['test'][index]['dialogue']
summary = dataset['test'][index]['summary']

prompt = f"""
Summarize the following conversation.

{dialogue}

Summary:
"""

inputs = tokenizer(prompt, return_tensors='pt').to(device)

output = tokenizer.decode(
    original_model.generate(
        inputs["input_ids"],
        max_new_tokens=200,
    )[0],
    skip_special_tokens=True
)

dash_line = '-'.join('' for x in range(100))

print(dash_line)
print(f'INPUT PROMPT:\n{prompt}')
print(dash_line)
print(f'BASELINE HUMAN SUMMARY:\n{summary}\n')
print(dash_line)
print(f'MODEL GENERATION - ZERO SHOT:\n{output}')

"""**Notes**

The original FLAN-T5 model can identify the general topic of the dialogue in zero-shot inference, but its summary is incomplete. It extracts a relevant sentence instead of generating a full human-like summary. This shows why fine-tuning can improve the model for the dialogue summarization task.

**2 - Perform Full Fine-Tuning**

**2.1 — Preprocess the Dialog-Summary Dataset**
"""

def tokenize_function(example):
    start_prompt = 'Summarize the following conversation.\n\n'
    end_prompt = '\n\nSummary: '
    prompt = [start_prompt + dialogue + end_prompt for dialogue in example["dialogue"]]

    example['input_ids'] = tokenizer(
        prompt,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    ).input_ids

    example['labels'] = tokenizer(
        example["summary"],
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    ).input_ids

    return example

tokenized_datasets = dataset.map(tokenize_function, batched=True)

tokenized_datasets = tokenized_datasets.remove_columns(
    ['id', 'topic', 'dialogue', 'summary']
)

tokenized_datasets = tokenized_datasets.filter(
    lambda example, index: index % 100 == 0,
    with_indices=True
)

print(f"Shapes of the datasets:")
print(f"Training: {tokenized_datasets['train'].shape}")
print(f"Validation: {tokenized_datasets['validation'].shape}")
print(f"Test: {tokenized_datasets['test'].shape}")

print(tokenized_datasets)

"""**Notes**

The DialogSum dataset was successfully preprocessed for fine-tuning. Each dialogue was converted into an instruction prompt and tokenized into input_ids, while each human summary was tokenized into labels. The dataset was then reduced to a smaller subset to make training faster during the lab.

"""

output_dir = f'./dialogue-summary-training-{str(int(time.time()))}'

training_args = TrainingArguments(
    output_dir=output_dir,
    learning_rate=1e-5,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_steps=1,
    max_steps=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    report_to="none",
    fp16=False,
    bf16=False,
    save_strategy="no"
)

trainer = Trainer(
    model=original_model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['validation']
)

trainer.train()

"""**Notes**

The full fine-tuning pipeline was prepared, but running full training in the current Colab environment was too slow. This is expected because full fine-tuning updates all model parameters and requires more compute and memory resources.
"""

!ls -al ./flan-dialogue-summary-checkpoint/

from datasets import load_dataset, DatasetDict

huggingface_dataset_name = "knkarthick/dialogsum"
dataset = load_dataset(huggingface_dataset_name)

print(dataset)

from datasets import DatasetDict
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, DataCollatorForSeq2Seq

demo_model_name = "google/flan-t5-small"

demo_tokenizer = AutoTokenizer.from_pretrained(demo_model_name)

raw_tiny_dataset = DatasetDict({
    "train": dataset["train"].shuffle(seed=42).select(range(24)),
    "validation": dataset["validation"].shuffle(seed=42).select(range(4)),
    "test": dataset["test"].shuffle(seed=42).select(range(4))
})

def tokenize_demo_function(example):
    start_prompt = "Summarize the following conversation.\n\n"
    end_prompt = "\n\nSummary:"

    prompts = [
        start_prompt + dialogue + end_prompt
        for dialogue in example["dialogue"]
    ]

    model_inputs = demo_tokenizer(
        prompts,
        max_length=256,
        truncation=True
    )

    labels = demo_tokenizer(
        text_target=example["summary"],
        max_length=64,
        truncation=True
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

tokenized_tiny_dataset = raw_tiny_dataset.map(
    tokenize_demo_function,
    batched=True,
    remove_columns=raw_tiny_dataset["train"].column_names
)

print(tokenized_tiny_dataset)

"""**Notes**

The small DialogSum dataset was successfully preprocessed for the educational fine-tuning experiment. Dialogues were converted into instruction prompts and tokenized as input_ids, while summaries were tokenized as labels. The resulting dataset is ready for a lightweight training demonstration.

**2.2 — Load Demo Model and Generate Baseline Before Training**
"""

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

demo_model = AutoModelForSeq2SeqLM.from_pretrained(demo_model_name).to(device)

def generate_demo_summary(model, dialogue):
    prompt = f"""
Summarize the following conversation.

{dialogue}

Summary:
"""
    inputs = demo_tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(device)

    output_ids = model.generate(
        inputs["input_ids"],
        max_new_tokens=80
    )

    return demo_tokenizer.decode(output_ids[0], skip_special_tokens=True)

test_dialogues = raw_tiny_dataset["test"]["dialogue"]
human_summaries = raw_tiny_dataset["test"]["summary"]

before_training_summaries = []

for dialogue in test_dialogues:
    before_training_summaries.append(generate_demo_summary(demo_model, dialogue))

print("Baseline generated summaries before training:")

for i, summary in enumerate(before_training_summaries):
    print(f"\nExample {i + 1}:")
    print(summary)

"""**Notes**

The small FLAN-T5 model generated baseline summaries before training. The outputs were incomplete and often copied short parts of the dialogue, which provides a useful baseline for comparing the effect of the mini fine-tuning step.

**Mini Fine-Tune the Model with the Preprocessed Dataset**
"""

from transformers import TrainingArguments, Trainer
import time

data_collator = DataCollatorForSeq2Seq(
    tokenizer=demo_tokenizer,
    model=demo_model
)

output_dir = f'./demo-dialogue-summary-training-{str(int(time.time()))}'

demo_training_args = TrainingArguments(
    output_dir=output_dir,
    learning_rate=1e-4,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    max_steps=5,
    logging_steps=1,
    save_strategy="no",
    report_to="none"
)

demo_trainer = Trainer(
    model=demo_model,
    args=demo_training_args,
    train_dataset=tokenized_tiny_dataset["train"],
    eval_dataset=tokenized_tiny_dataset["validation"],
    data_collator=data_collator
)

demo_trainer.train()

"""**Notes**

The mini fine-tuning process ran successfully using FLAN-T5-small and a tiny subset of DialogSum. The model completed 5 training steps, confirming that the preprocessing, Trainer configuration, data collator, and training pipeline work correctly. This lightweight experiment demonstrates the full fine-tuning workflow without requiring the heavy compute resources needed for FLAN-T5-base.

**2.3 — Evaluate the Model Qualitatively**
"""

after_training_summaries = []

for dialogue in test_dialogues:
    after_training_summaries.append(generate_demo_summary(demo_model, dialogue))

dash_line = "-".join("" for x in range(100))

for i in range(len(test_dialogues)):
    print(dash_line)
    print(f"Example {i + 1}")
    print(dash_line)
    print("HUMAN BASELINE SUMMARY:")
    print(human_summaries[i])
    print(dash_line)
    print("MODEL BEFORE MINI FINE-TUNING:")
    print(before_training_summaries[i])
    print(dash_line)
    print("MODEL AFTER MINI FINE-TUNING:")
    print(after_training_summaries[i])
    print()

"""**Notes**

The mini fine-tuning process changed the model outputs, which confirms that training affected the model. However, because the training used only a tiny dataset and 5 training steps, the generated summaries did not consistently improve. This shows that fine-tuning requires enough data, training steps and compute resources to produce meaningful improvements.

**2.4 — Evaluate the Model Quantitatively with ROUGE**
"""

import evaluate
import numpy as np

rouge = evaluate.load("rouge")

before_results = rouge.compute(
    predictions=before_training_summaries,
    references=human_summaries,
    use_aggregator=True,
    use_stemmer=True
)

after_results = rouge.compute(
    predictions=after_training_summaries,
    references=human_summaries,
    use_aggregator=True,
    use_stemmer=True
)

print("BEFORE MINI FINE-TUNING:")
print(before_results)

print("\nAFTER MINI FINE-TUNING:")
print(after_results)

print("Absolute improvement after mini fine-tuning:")

improvement = (
    np.array(list(after_results.values())) -
    np.array(list(before_results.values()))
)

for key, value in zip(after_results.keys(), improvement):
    print(f"{key}: {value * 100:.2f}%")

"""**Conclusion Notes**

* The lightweight full fine-tuning experiment successfully demonstrated the complete fine-tuning workflow. The dataset was preprocessed into input_ids and labels, a small FLAN-T5 model was trained for 5 steps, and the model was evaluated qualitatively and quantitatively.

* The qualitative evaluation showed that the model outputs changed after training, although the summaries were still not consistently human-quality due to the tiny dataset and very limited number of training steps.

* The ROUGE evaluation showed measurable improvement after mini fine-tuning: rouge1 improved by 17.71%, rouge2 by 3.12%, rougeL by 14.07%, and rougeLsum by 14.07%. This confirms that fine-tuning can improve task alignment, but meaningful performance requires more training data, more steps, and stronger compute resources.

**3 - Perform Parameter Efficient Fine-Tuning (PEFT)**

**3.1 — Setup the PEFT/LoRA model for Fine-Tuning**
"""

def print_number_of_trainable_model_parameters(model):
    trainable_model_params = 0
    all_model_params = 0

    for _, param in model.named_parameters():
        all_model_params += param.numel()
        if param.requires_grad:
            trainable_model_params += param.numel()

    percentage = 100 * trainable_model_params / all_model_params

    return (
        f"trainable model parameters: {trainable_model_params}\n"
        f"all model parameters: {all_model_params}\n"
        f"percentage of trainable model parameters: {percentage:.2f}%"
    )

from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    r=32,
    lora_alpha=32,
    target_modules=["q", "v"],
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.SEQ_2_SEQ_LM
)

peft_demo_model = get_peft_model(
    demo_model,
    lora_config
)

print(print_number_of_trainable_model_parameters(peft_demo_model))

"""**Notes**

The PEFT/LoRA setup was successful. Instead of training all model parameters, LoRA reduced the trainable parameters to only 1.76% of the model. This demonstrates the main advantage of parameter-efficient fine-tuning: adapting a model to a specific task using far fewer compute and memory resources than full fine-tuning.

**3.2 — Train PEFT Adapter**
"""

output_dir = f'./peft-demo-dialogue-summary-training-{str(int(time.time()))}'

peft_training_args = TrainingArguments(
    output_dir=output_dir,
    auto_find_batch_size=True,
    learning_rate=1e-3,
    num_train_epochs=1,
    logging_steps=1,
    max_steps=5,
    save_strategy="no",
    report_to="none"
)

peft_trainer = Trainer(
    model=peft_demo_model,
    args=peft_training_args,
    train_dataset=tokenized_tiny_dataset["train"],
    data_collator=data_collator
)

peft_trainer.train()

"""**3.3 — Evaluate the Model Qualitatively**"""

peft_demo_model.eval()

def generate_peft_summary(model, dialogue):
    prompt = f"""
Summarize the following conversation.

{dialogue}

Summary:
"""
    inputs = demo_tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(device)

    output_ids = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=80
    )

    return demo_tokenizer.decode(
        output_ids[0],
        skip_special_tokens=True
    )

peft_after_training_summaries = []

for dialogue in test_dialogues:
    peft_after_training_summaries.append(
        generate_peft_summary(peft_demo_model, dialogue)
    )

dash_line = "-".join("" for x in range(100))

for i in range(len(test_dialogues)):
    print(dash_line)
    print(f"Example {i + 1}")
    print(dash_line)
    print("HUMAN BASELINE SUMMARY:")
    print(human_summaries[i])
    print(dash_line)
    print("MODEL BEFORE MINI FINE-TUNING:")
    print(before_training_summaries[i])
    print(dash_line)
    print("FULL MINI FINE-TUNING MODEL:")
    print(after_training_summaries[i])
    print(dash_line)
    print("PEFT / LORA MODEL:")
    print(peft_after_training_summaries[i])
    print()

"""**Notes**

The qualitative evaluation shows that the PEFT/LoRA model changed the model behavior and often produced more summary-like outputs than the original baseline. In several examples, the PEFT model captured more context than the original model and produced more complete responses than the mini full fine-tuned model. However, the summaries were still imperfect because the experiment used a very small dataset and only 5 training steps. This confirms that PEFT can efficiently adapt a model, but meaningful performance still requires enough data and training time.

**3.4 — Evaluate the Model Quantitatively with ROUGE Metric**
"""

rouge = evaluate.load("rouge")

peft_results = rouge.compute(
    predictions=peft_after_training_summaries,
    references=human_summaries,
    use_aggregator=True,
    use_stemmer=True
)

print("BEFORE MINI FINE-TUNING:")
print(before_results)

print("\nFULL MINI FINE-TUNING:")
print(after_results)

print("\nPEFT / LORA MODEL:")
print(peft_results)

print("Absolute improvement of PEFT over original baseline:")

improvement = (
    np.array(list(peft_results.values())) -
    np.array(list(before_results.values()))
)

for key, value in zip(peft_results.keys(), improvement):
    print(f"{key}: {value * 100:.2f}%")

print("Absolute difference of PEFT compared to full mini fine-tuning:")

difference = (
    np.array(list(peft_results.values())) -
    np.array(list(after_results.values()))
)

for key, value in zip(peft_results.keys(), difference):
    print(f"{key}: {value * 100:.2f}%")

"""**Conclusion Notes Lab 2**

**Fine-Tuning and PEFT/LoRA for Dialogue Summarization :**


* This lab demonstrated the full workflow of adapting a generative AI model for dialogue summarization. The original FLAN-T5 model was tested with zero-shot inference, then the dataset was preprocessed into input_ids and labels for training.

* Full fine-tuning was shown to be computationally expensive because it requires updating all model parameters. To understand the process in a lightweight way, a small FLAN-T5 model was fine-tuned on a tiny subset of DialogSum. The mini fine-tuning experiment changed the model outputs and improved ROUGE scores compared to the original baseline.

* The lab also demonstrated Parameter Efficient Fine-Tuning using LoRA. Instead of training the entire model, LoRA trained only 1.76% of the parameters. Despite using far fewer trainable parameters, the PEFT/LoRA model achieved better ROUGE scores than the original baseline and slightly better results than the mini full fine-tuning experiment.

* Overall, the lab shows that fine-tuning can improve task-specific performance, but full fine-tuning requires significant compute resources. PEFT/LoRA provides a more efficient alternative by adapting the model with fewer trainable parameters while still achieving meaningful performance improvements.
"""